### ISSUE TITLE
aptreader throws an exception if a package's Maintainer field is empty

### ISSUE THREAD

**Issue by cxcorp** [gliese1337/apt-client#9]
Hey. Thanks for putting this package out!

I'm trying to parse the default APT lists of a Raspberry Pi Zero W, but noticed that there's a package in there which causes aptreader to throw an exception. 

The source list is
```
deb http://archive.raspberrypi.org/debian/ buster main
```

which the library resolves to the following URL (not sure if the `//` is intended behavior?):

http://archive.raspberrypi.org/debian//dists/buster/main/binary-armhf/Packages

and the package definition (or rather, one of the few) which causes the parser to fail is:

```
Package: kodi
Architecture: all
Breaks: xbmc (<< 2:14.0~git20141019), xbmc-data, xbmc-standalone
Depends: kodi-bin (>= 2:18.7-1~buster), kodi-bin (<< 2:18.7-1~buster.1~), curl, libcurl4 | libcurl3, mesa-utils, x11-utils, fonts-liberation | ttf-liberation, fonts-dejavu-core | ttf-dejavu-core, python-bluez | python-lightblue, python-imaging | python-pil, python-simplejson, libass9 | libass5 | libass4, libgif5 | libgif7, libnfs12 | libnfs8 | libnfs4 | libnfs1, libbluray1 | libbluray2, libshairplay0, libvorbisfile3, libaacs0, libcec4, libgnutls30 | libgnutls-deb0-28 | libgnutls28 | libgnutls26, libxslt1.1, libegl1, libgles2, policykit-1
Priority: optional
Section: video
Filename: pool/main/k/kodi/kodi_18.7-1~buster_all.deb
Size: 22932518
SHA256: d6f32afbf32540a76ea72b50d90a5f32175b04e88cc0282e78c40c213beee3ac
SHA1: 15682fae6cedfc74bd82c32f2437572f4fdcfb1a
MD5sum: d91d467be1973f66916de39af2b9a6cc
Description: Kodi Media Center (arch-independent data package)
 Kodi, formerly known as XBMC Media Center, is an award winning free and open
 source software media-player and entertainment hub for all your digital media.
 Kodi is available for Linux, Mac OS X (Leopard, Tiger and Apple TV) and
 Microsoft Windows, as well as the original Xbox game console. Created in 2003
 by a group of like minded programmers, Kodi is a non-profit project run and
 developed by volunteers located around the world. More than 50 software
 developers have contributed to Kodi, and 100-plus translators have worked to
 expand its reach, making it available in more than 30 languages.
 .
 While Kodi functions very well as a standard media player application for your
 computer, it has been designed to be the perfect companion for your HTPC.
 Supporting an almost endless range of remote controls, and combined with its
 beautiful interface and powerful skinning engine, Kodi feels very natural to
 use from the couch and is the ideal solution for your home theater. Once
 installed, your computer will become a fully functional multimedia jukebox.
 .
 This package contains Kodi's architecture independent data.
Homepage: http://kodi.tv
Maintainer:  <>
Provides: kodi-data, kodi-skin-estuary, kodi-standalone, xbmc, xbmc-data, xbmc-standalone
Recommends: libvdpau1, libva-intel-vaapi-driver, libva1
Replaces: xbmc (<< 2:14.0~git20141019), xbmc-data, xbmc-standalone
Source: kodi
Suggests: kodi-pvr-mythtv, kodi-pvr-vuplus, kodi-pvr-vdr-vnsi, kodi-pvr-njoy, kodi-pvr-nextpvr, kodi-pvr-mediaportal-tvserver, kodi-pvr-tvheadend-hts, kodi-pvr-dvbviewer, kodi-pvr-argustv, kodi-pvr-iptvsimple, kodi-audioencoder-vorbis, kodi-audioencoder-flac, kodi-audioencoder-lame
Version: 2:18.7-1~buster
Installed-Size: 38801
```

As you can see, the Maintainer field is empy, which causes the following error to be thrown:

```
Exception has occurred: TypeError: Cannot read property 'replace' of undefined
  at toContactInfo (/home/user/Projects/apt-testing/node_modules/apt-client/dist/aptreader.js:55:12)
    at /home/user/Projects/apt-testing/node_modules/apt-client/dist/aptreader.js:248:32
    at Generator.next (<anonymous>)
    at fulfilled (/home/user/Projects/apt-testing/node_modules/apt-client/dist/aptreader.js:15:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

which resolves to the following line:

https://github.com/gliese1337/apt-client/blob/bcb7f9c0e5ca99d5be055e66d85d02e138fc9b26/src/aptreader.ts#L131

The `toContactInfo` function gets called with the `s` parameter being `'<>'`, so the first regexes match, but after being destructured, the first capture group (`name`) is `undefined`, causing the error at hand.

**Comment by gliese1337** [comment]
Thanks for the extensive debugging info! That made it pretty easy to fix. I've added that specific repository on which you were seeing errors to the test cases and published a new minor version with the fix.

**Comment by cxcorp** [comment]
Super! Thanks for the fantastically quick fix!
